Global:
  reader_config: configs/yolo_reader.yml
  input_list: ['scale_factor']
  Evaluation: True
  model_dir: ./ppyolo_r18vd_coco_cells_aug
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2

Quantization:
  activation_quantize_type: 'range_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 5000
  eval_iter: 1000
  learning_rate: 0.0001
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05
  #origin_metric: 0.289

