metric: COCO
num_classes: 1

# Datset configuration
TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/train.json
    dataset_dir: cells_coco/

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: test.json
    dataset_dir: cells_coco/

worker_num: 0

# preprocess reader in test
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
